<link rel='stylesheet' type='text/css'
	href='<?php echo $this->baseUrl('css/style_facture.css')?>' />
<link rel='stylesheet' type='text/css'
	href='<?php echo $this->baseUrl('css/print.css')?>' media="print" />
<script type='text/javascript'
	src='<?php echo $this->baseUrl('js/jquery-1.3.2.min.js')?>'></script>
<script type='text/javascript'
	src='<?php echo $this->baseUrl('js/example.js')?>'></script>



<div id="content">


	<div id="page-wrap">

		<textarea id="header">FACTURE</textarea>

		<div id="identity">



			<div id="logo">

				<div id="logoctr"></div>

				<div id="logohelp">
					<input id="imageloc" type="text" size="50" value="" /><br /> (max
					width: 540px, max height: 100px)
				</div>
				<img id="image" src="<?php echo $this->baseUrl('images/logo.png')?>"
					alt="logo" />
			</div>

		</div>

		<div style="clear: both"></div>

		<div id="customer">
			<h3>
				<a
					href="<?php echo $this->url(array('controller' => 'client', 'action' => 'profil' ),'default',true);?>">Client
					: </a> Khalifa RMILI Societe XXXXXX
			</h3>

			<!--  <textarea id="customer-title" readonly="readonly">
</textarea >-->

			<table id="meta">
				<tr>
					<td class="meta-head"><a
						href="<?php echo $this->url(array('controller' => 'commande', 'action' => 'index' ),'default',true);?>">Commande
							N°</a></td>
					<td><textarea>000123</textarea></td>
				</tr>
				<tr>

					<td class="meta-head">Date</td>
					<td><textarea id="date">December 15, 2009</textarea></td>
				</tr>
			</table>

		</div>

		<table id="items">

			<tr>
				<th>Type</th>
				<th>Description</th>
				<th>Prix Unitaire</th>
				<th>Quantité</th>
				<th>Prix</th>

			</tr>
			<!--  Projets -->
			<tr class="tr_titre">
				<td colspan="5"><div class="delete-wpr">
						<a
							href="<?php echo $this->url(array('controller' => 'project', 'action' => 'index' ),'default',true);?>">Projets</a>
					</div></td>


			</tr>

			<tr class="item-row projet">
				<td class="item-name"><div class="delete-wpr">
						<textarea>Site Web</textarea>
						<a class="delete" href="javascript:;" title="Remove row">X</a>
					</div></td>
				<td class="description"><textarea>Site web dynamique</textarea></td>
				<td><textarea class="cost">10000</textarea></td>
				<td><textarea class="qty">1</textarea></td>
				<td><span class="price"></span></td>

			</tr>

			<tr id="hiderow">
				<td colspan="5"><a id="addrow-projet" href="javascript:;"
					title="Add a row">Ajouter un projet</a></td>
			</tr>

			<!--  Services -->

			<tr class="tr_titre">
				<td colspan="5"><div class="delete-wpr">
						<a
							href="<?php echo $this->url(array('controller' => 'service', 'action' => 'index' ),'default',true);?>">Service
							:</a>
					</div></td>
			</tr>

			<tr class="item-row service">
				<td class="item-name"><div class="delete-wpr">
						<textarea>Hebergement</textarea>
						<a class="delete" href="javascript:;" title="Remove row">X</a>
					</div></td>
				<td class="description"><textarea>Packe professionnel</textarea></td>
				<td><textarea class="cost">3000</textarea></td>
				<td><textarea class="qty">1</textarea></td>
				<td><span class="price"></span></td>

			</tr>

			<tr id="hiderow">
				<td colspan="5"><a id="addrow-service" href="javascript:;"
					title="Add a row">Ajouter un service</a></td>
			</tr>
			<tr>

				<td colspan="2" class="blank"></td>
				<td colspan="2" class="total-line" align="left">Total HT</td>
				<td class="total-value"><div id="total" align="center"></div></td>
			</tr>
			<tr>
				<td colspan="2" class="blank"></td>
				<td colspan="2" class="total-line">TVA 20 %</td>
				<td class="total-value"><div id="tva" align="center"></div></td>



				<!--  <td class="total-value"><textarea id="tva"></textarea></td>-->
			</tr>
			<tr>
				<td colspan="2" class="blank"></td>
				<td colspan="2" class="total-line balance">Total TTC</td>
				<td class="total-value balance"><div class="avec-tva" align="center"></div></td>
			</tr>

		</table>
		<div id="customer">
			<div id="direction">
				<br> <textarea id="customer-title">La Direction Générale </textarea>
					<br> <br> <br> <br> <br>
			</div>
		</div>

		<div id="terms">
			<textarea id="footer">Tous Vos Besoins pour Votre réussite</textarea>
			<textarea id="address">Tynex Media, Imm. Oasis, B1 Bureau N° 128 Amsernat 80 00 0 Agadir
Tél: +212 (0)5 28 29 25 95 Mobile: +212 (0)6 41 32 64 07
Email: contact@tynexmedia.com
Agadir - Maroc</textarea>
		</div>
	</div>

</div>