<script type="text/javascript"
	src="<?php echo $this->baseUrl('js/commande.js');?>"></script>

<h5 class="test"></h5>

<a class="button green morph"
		href="<?php echo $this->url(array('controller' => 'commande', 'action' => 'add' ),'default',true);?>">+ Ajouter</a>
	
	<a class="delete_b_commande button pink morph">- Supprimer</a>
 <a class="selectall button blue morph">De/Selectionner tous</a>
<?php
$i = 0;
$nom_client = NULL;
echo '
<div id="UITab">

<div class="tab_container">

<div id="tab1" class="tab_content">
<div class="load_page">

<form>
<div class="tableName inTab">
<h3 id="test"></h3>
<table class="display data_table2 commande"  id="data_table3">
<thead>
<tr>

<th align="left">Id</th>
<th>Description</th>
<th>Client</th>
<th>Action</th>
</tr>
</thead>
<tbody>';

foreach ( $this->list_commandes as $commande ) {
	echo '<tr>
<td  class="id_commande" align ="left">' . $commande ['id_commande'] . '</td>
<td class="nom_commande">' . $commande ['libelle_commande'] . '</td>';

//get the client name
foreach($this->list_clients as $client){
	if($client['id_client'] == $commande ['id_client'])
	{
		if($client['type'] == 'Entreprise'){
			$nom_client = $client['societe'];
		}else{
			$nom_client = $client['nom'];
		}
	}
}
echo '
<td>' . $nom_client . '</td>

<td>
<span class="tip" >
<a  title="Edit" class="edit" href="';
echo $this->url(array('id' => $commande ['id_commande']),'commandemodify');
echo '">
<img src="images/icon/icon_edit.png" >
</a>
</span>
<span class="tip" >
<a id="' . $i . '" class="Delete"  name="Band ring" title="Delete">
<img src="images/icon/icon_delete.png">
</a>
</span>
</td>
</tr>';
	$i ++;
};
echo '</tbody>
</table>
</div>
</form>
</div>
</div><!--tab1-->

</div>
</div><!-- End UITab -->
<!-- clear fix -->
<div class="clear"></div>
';
?>