
<script type="text/javascript"
	src="<?php echo $this->baseUrl('js/projet.js');?>"></script>
<script type="text/javascript"
	src="<?php echo $this->baseUrl('js/sliders.js');?>"></script>
<link rel="stylesheet" type="text/css"
	href="<?php echo $this->baseUrl('css/styles.css');?>" />
	<script type="text/javascript">
<!--
$(document).ready(function(){
	$('a.progression').html('0');
	$('a.progression').attr('value','0');
	$('div.slider-handle').css({'top':'188px'});
	$('div.cu-mid').css({'height':'0px'});
	//drag and drop
	for(var i=1;i<4;i++){
		$('.p'+i).draggable({
			cursor: 'move',
			containment : 'parent',
			helper : 'clone',
			revert: true,
			axis: "x"
		});
	}
	$('.current_priority').droppable({
			drop : change_priority
	});
	function change_priority(event, ui){
			var choix = ui.draggable;
			var class_choix = choix.attr('p');
			var new_src = '/images/'+class_choix+'.png';
			$(this).attr('src',new_src);
			$('.priority_hidden').attr('value',class_choix);
		};
});
//-->
</script>
<?php 

echo  '<form id="add_projet" class="f_p_add">';
echo '<div class="section commande">
<label>Commande<small>La commande à laquel ce projet appartient</small></label>
<div>
<select data-placeholder="Veuillez choisir une commande..."
class="chzn-select" tabindex="2">
<option value=""></option>';
foreach($this->list_commandes as $commande){
	echo "<option value=".$commande['id_commande'].">".$commande['id_commande']."</option>";
}
echo '</select><span class="f_help">Veuillez choisir un client</span>
</div>
</div>';
echo '<div class="section type_projet">
<label>Type de projet<small>Définir le type de ce projet</small></label>
<div>
<select data-placeholder="Veuillez choisir un type de projet..."
class="chzn-select " tabindex="2">
<option value=""></option>';
foreach($this->list_types_projets as $type_projet){
	echo "<option value=".$type_projet['nom_type_projet'].">".$type_projet['nom_type_projet']."</option>";
}
echo '</select><span class="f_help">Veuillez choisir un type de projet</span>
</div>
</div>';

echo '
<div class="section">
		<label>Date debut</label>
		<div>
			<input type="text" id="datepick" class="datepicker date_debut"
				readonly="readonly" name="date_debut" />
		</div>
	</div>

	<div class="section">
		<label>Date fin</label>
		<div>
			<input type="text" id="datepick2" class="datepicker date_fin"
				readonly="readonly" name="date_fin" />
		</div>
	</div>
	<div class="section alphaonly">
		<label>Description<small>Un petit mot sur le projet</small></label>
		<div>
			<textarea name="description"></textarea>
		</div>
	</div>
	<div class="section">
		<label>Status<small>Veuillez definir un status initial pour ce projet</small></label>
		<div>
			<input type="checkbox" id="status" name="status" class="status"
				value="1" /> <span class="f_help"></span>
				<input value="interrompu" type="hidden" id="status_hidden" name="status_hidden" class="status_hidden"
				value="" />
		</div>
	</div>
	<div class="section">
		<label>Paiement<small>Si le client à payer ou non pour ce projet</small></label>
		<div>
			<input type="checkbox" id="paye" name="paye" class="paye"
				value="1" /> <span class="f_help"></span>
				<input value="Non" type="hidden" id="paye_hidden" name="paye_hidden" class="paye_hidden" />
		</div>
	</div>';
	echo '	
	<div class="section">
		<label> Employe <small>Définir la liste des employés qui travaillent dans ce projet</small></label>
		<div>
			<select class="chzn-select emplyes" multiple tabindex="4">
				<option value=""></option>';
foreach($this->list_employes as $employe)
{
	echo "<option value=".$employe['nom'].">".$employe['nom']."</option>";
}
					
echo'	</select>
		</div>
	</div>
	<div class="section">
     <label>Prix<small>Donner un prix</small></label>
         <div>
             <input type="text" id="sStep" value="1000.00" name="prix" class="prix_projet"/>
           </div>
     </div>';
//add drag and drop
echo '
	<div class="section">
     <label>Priorité<small>Donner une priorité pour ce projet</small></label>
         <div>
         <img class="current_priority" src="'.$this->baseUrl('images/p3.png').'" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
         &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
         <img class="p1" p="p3" src="'.$this->baseUrl('images/p3.png').'" />
         <img class="p2" p="p2" src="'.$this->baseUrl('images/p2.png').'" />
         <img class="p3" p="p1" src="'.$this->baseUrl('images/p1.png').'" />
         <input value="p3" type="hidden" id="priority_hidden" name="priority_hidden" class="priority_hidden" />
           </div>
   </div>';  
echo '     
	<div class="section">
		<label>Progression<small>Vous pouvez définir une progression pour votre projet</small></label>
		<div style="font-size:2em ; margin :10 10 20 10"><a class="uibutton normal progression">23%</a></div>
		<div>
	<div class="main">

    <!-- The sliders -->
    
    <div class="colorful-slider blue">
    <div class="slider-handle"></div>
    </div>

    <div class="cube-area">
    
        <!-- The colorful bars -->
        
        <div class="cuboid blue">
        <div class="cu-top"></div>
        <div class="cu-mid"></div>
        <div class="cu-bottom"></div>
        </div>
      
        <!-- The perspective div is CSS3 transformed -->
        
        <div class="perspective">
        </div>
    </div>
    
    <!-- Old school float clearing -->
    <div class="clear"></div>
</div>
</div>
<br><br>
</div>

	<div class="section last">
		<div>
			<a class="button green morph add_projet">Ajouter</a> 
		</div>
	</div>

</form>';
?>
