
<script type="text/javascript"
	src="<?php echo $this->baseUrl('js/type_projet.js');?>"></script>


<form id="validation" class="f_t_p_add">
	<div class="section textonly">
		<label> Nom du type de projet <small>Une description pour ce type de projet</small></label>
		<div>
			<input id="f_required" name="nom_type_projet" type="text"
				class="validate[required] medium">
		</div>
	</div>
	<div class="section last">
		<div>
			<a class="button green morph add_type_projet">Ajouter</a> 
		</div>
	</div>
	
</form>