<script type="text/javascript"
	src="<?php echo $this->baseUrl('js/type_projet.js');?>"></script>

<h5 class="test"></h5>
<form action="#" id="validation" class="f_t_p_modify">
	<div class="section textonly">
		<label> Type du projet <small></small></label>
		<div>
			<input name="nom_type_projet" type="text" class="medium" value="<?php echo $this->type_projet->nom_type_projet;?>">
		</div>
	</div>
	
	<div class="section last">
		<div>
			<a class="button green morph modify_type_projet">Appliquer la modification</a>
		</div>
	</div>
	<div>
			<input name="id_type_projet" type="hidden" value="<?php echo $this->type_projet->id_type_projet;?>">
		</div>

</form>