
<script type="text/javascript"
	src="<?php echo $this->baseUrl('js/typeservice.js');?>"></script>


<form id="validation" class="f_t_s_add">
	<div class="section textonly">
		<label> Libellé du type de service <small>Une sorte de description pour ce type de service</small></label>
		<div>
			<input id="f_required" name="libelle_typeservice" type="text"
				class="validate[required] medium">
		</div>
	</div>
	<div class="section last">
		<div>
			<a class="button green morph add_typeservice">Ajouter</a> 
		</div>
	</div>
	
</form>