<script type="text/javascript"
	src="<?php echo $this->baseUrl('js/typeservice.js');?>"></script>

<h5 class="test"></h5>

<a class="button green morph"
		href="<?php echo $this->url(array('controller' => 'typeservice', 'action' => 'add' ),'default',true);?>">+ Ajouter</a>
	
	<a class="delete_b button pink morph">- Supprimer</a>
 <a class="selectall button blue morph">De/Selectionner tous</a>
<?php
$i = 0;
echo '
<div id="UITab">

<div class="tab_container">

<div id="tab1" class="tab_content">
<div class="load_page">

<form>
<div class="tableName inTab">
<h3 id="test"></h3>
<table class="display data_table2 typeservice"  id="data_table3">
<thead>
<tr>

<th align="left">Id</th>
<th>Description</th>
<th>Action</th>
</tr>
</thead>
<tbody>';

foreach ( $this->list_typeservices as $typeservice ) {
	echo '<tr>
<td  class="id_typeservice" align ="left">' . $typeservice ['id_type_service'] . '</td>
<td class="nom_typeservice">' . $typeservice ['libelle_type_service'] . '</td>
<td>
<span class="tip">
<a  title="Edit" class="edit" href="';
echo $this->url(array('id' => $typeservice ['id_type_service']),'typeservicemodify');
echo '">
<img src="images/icon/icon_edit.png" >
</a>
</span>
<span class="tip" >
<a id="' . $i . '" class="Delete"  name="Band ring" title="Delete">
<img src="images/icon/icon_delete.png">
</a>
</span>
</td>
</tr>';
	$i ++;
};
echo '</tbody>
</table>
</div>
</form>
</div>
</div><!--tab1-->

</div>
</div><!-- End UITab -->
<!-- clear fix -->
<div class="clear"></div>
';
?>