
<script type="text/javascript"
	src="<?php echo $this->baseUrl('js/pack.js');?>"></script>
<h5 class="test"></h5>
<?php 
// Affichage du type de service
$type_service_string = NULL;
foreach ( $this->list_types_services as $type_service ) {
	if ($type_service ['id_type_service'] == $this->pack->id_type_service) {
		$type_service_string = $type_service ['libelle_type_service'];
	}
}
echo '
<form id="validation" class="f_p_modify">';

echo '<div class="section">
		<label> Id <small></small></label>
		<div>
			<input disabled="disabled" id="id" name="id" type="text" class="validate[required] medium id_pack" maxlength="20" value="' . $this->pack->id_pack . '">
		</div>
	</div>';

echo '<div class="section">
	<label>Type de service<small>Veuillez choisir un type de service pour ce nouveau pack</small></label>
	<div>
	<select data-placeholder="'.$type_service_string.'"
	class="chzn-select" tabindex="2">
	<option value=""></option>';
foreach($this->list_types_services as $type_service){
	echo "<option value=".$type_service['nom_type_service'].">".$type_service['libelle_type_service']."</option>";
}
echo '</select><span class="f_help">Veuillez choisir un type de services</span>
	</div>
	</div>';
	echo '<div class="section textonly">
		<label> libellé du pack <small>Donner un libellé pour ce pack</small></label>
		<div>
			<input id="f_required" name="nom_pack" type="text"
				class="validate[required] medium nom_pack" value="'.$this->pack->libelle_pack.'">
		</div>
	</div>
	<div class="section last">
		<div>
			<a class="button blue morph modify_pack">Appliquer les modifications</a> 
		</div>
	</div>
	
</form>';
?>