<script type="text/javascript"
	src="<?php echo $this->baseUrl('js/employe.js');?>"></script>
<script type="text/javascript">
$(document).ready(function(){
			//check the right gender 'homme' ou 'femme'
			if($('.hidden_gender').attr('value') == 0){
					$('label[for="radio-1"]').addClass('checked');
					$('label[for="radio-2"]').removeClass('checked');

				}else{
					$('label[for="radio-2"]').addClass('checked');
					$('label[for="radio-1"]').removeClass('checked');
					}
});


</script>
<?php

echo '
<h5 class="test"></h5>
<form id="validation" class="f_e_modify">
	<div class="section">
		<label> Id <small></small></label>
		<div>
			<input disabled="disabled" id="id" name="id" type="text" class="validate[required] medium id_employe" maxlength="20" value="' . $this->employe->id_employe . '">
		</div>
	</div>
	<div class="section alphaonly">
		<label> Nom <small></small></label>
		<div>
			<input id="lastname" name="nom" type="text" class="validate[required] medium" maxlength="20" value="' . $this->employe->nom . '">
		</div>
	</div>
	<div class="section alphaonly">
		<label> Prénom <small></small></label>
		<div>
			<input id="firstname" name="prenom" type="text" class="validate[required] medium" maxlength="20" value="' . $this->employe->prenom . '">
		</div>
	</div>
	<div class="section ">
		<label>gender<small></small></label>
		<div>
			<div>
				<input type="radio" name="gender" id="radio-1" value="0"
					class="ck"/> 
					<label for="radio-1">Homme</label>
			</div>
			<div>
				<input type="radio" name="gender" id="radio-2" value="1"
					class="ck"  /> 
					<label for="radio-2">Femme</label>
			</div>
		</div>
	</div>
	<div class="section">
		<label> E-mail<small></small></label>
		<div>
			<input type="text" class="validate[required,custom[email]]  large email"
				name="email" id="e_required" value="' . $this->employe->email . '">
		</div>
	</div>
	<div class="section">
		<label> Adresse <small></small></label>
		<div>
			<input type="text" name="adresse" class=" full" value="' . $this->employe->adresse . '"/><span class="f_help"></span>
		</div>
	</div>
	<div class="section numericonly">
		<label> Telephone <small></small></label>
		<div>
			<input id="tel" name="tel" type="text" class="validate[required] small" maxlength="20" value="' . $this->employe->tel . '">
		</div>
	</div>

	<div class="section">
		<label> Compte d\'utilisateur <small></small></label>
		<div>
			<input type="text" name="username" id="username"
				class="validate[required,minSize[3],maxSize[20],] medium" value="' . $this->employe->username . '"/><label>Nom
				d\'utilisateur</label> <span class="f_help"> Doit etre compris entre 3 et 20 caractères.
			</span>
		</div>
		<div>
			<input type="password" class="validate[required,minSize[3]] medium"
				name="password" id="password" value="' . $this->employe->password . '"/><label>Mot de passe</label>
		</div>
		<div>
			<input type="password"
				class="validate[required,equals[password]] medium"
				name="passwordCon" id="passwordCon" value="' . $this->employe->password . '"/><label>Confirmer le mot de
				passe</label> <span class="f_help">Votre mot de passe doit contenir au moins 3 caractères.</span>
		</div>
	</div>';
// Affichage du poste
$poste_string = NULL;
foreach ( $this->list_postes as $poste ) {
	if ($poste ['id_poste'] == $this->employe->id_poste) {
		$poste_string = $poste ['nom_poste'];
	}
}
echo '<div class="section">
	<label>Poste<small></small></label>
	<div>
	<select data-placeholder="' . $poste_string . '"
	class="chzn-select" tabindex="2">
	<option value=""></option>';
foreach ( $this->list_postes as $poste ) {
	echo "<option value=" . $poste ['nom_poste'] . ">" . $poste ['nom_poste'] . "</option>";
}
echo '</select><span class="f_help">Veuillez choisir un poste</span>
	</div>
	</div>';
// affichage des occupations
echo '<div class="section">
		<label> Occupations courrantes <small>les occupations actuellement prise par cette employé</small></label>
		<div>
			<ul>';
if(count(($this->employe_occupations))>0)//compter le nombre d'occupation de cette employé
{
	foreach ( $this->employe_occupations as $employe_occupation ) {
		foreach ( $this->list_occupations as $occupation ) {
			if ($employe_occupation ['id_occup'] == $occupation ['id_occup']) {
				echo '<li ><em><strong>' . $occupation ['nom_occup'] . '</strong></em></li>';
			}
		}
	
	}
}else{
	echo '<li ><em><strong>Cette employé n\'a aucune occupation </strong></em></li>';
}
echo '<br/>';

echo '</ul>
		</div>
	</div>';

echo '	
	<div class="section">
		<label> Nouvelles occupation <small>utilisez cette solution pour définir de nouvelles occupations pour cette employé </small></label>
		<div>
			<select class="chzn-select" multiple tabindex="4">
				<option value=""></option>';
foreach ( $this->list_occupations as $occupation ) {
	echo "<option value=" . $occupation ['nom_occup'] . ">" . $occupation ['nom_occup'] . "</option>";
}

echo '	</select>
		</div>
	</div>';

echo'<div class="section last">
		<div>
			<a class="button blue morph submit_form modify_employe" data-icon="⏏">Appliquer la modification</a>
			<input class="hidden_gender" type="hidden" value="' . ($this->employe->genre == "Homme" ? "0" : "1") . '">
		</div>
	</div>
</form>
';
?>
