<script type="text/javascript"
	src="<?php echo $this->baseUrl('js/service.js');?>"></script>

<h5 class="test"></h5>

<a class="button green morph"
	href="<?php echo $this->url(array('controller' => 'service', 'action' => 'add' ),'default',true);?>">+
	Ajouter</a>

<a class="delete_b button pink morph">- Supprimer</a>
<a class="selectall button blue morph">De/Selectionner tous</a>

<?php
$i = 0;
echo '
<div id="UITab">

<div class="tab_container">

<div id="tab1" class="tab_content">
<div class="load_page">

<form>
<div class="tableName inTab">
<h3 id="test"></h3>
<table class="display data_table2 service"  id="data_table3">
<thead>
<tr>

<th align="left">Id</th>
<th>Date debut</th>
<th>Date fin</th>
<th>Status</th>
<th>Paiement</th>
<th>Type de service</th>
<th>Action</th>
</tr>
</thead>
<tbody>';

foreach ( $this->list_services as $service ) {
	
	echo '<tr>
	<td  class="id_service" align ="left">' . $service ['id_service'] . '</td>';
	
		echo '<td class="date_debut">' . $service ['date_debut'] . '</td>
		<td class="date_fin">' . $service ['date_fin'] . '</td>
		<td class="status">' . $service ['status'] . '</td>
		<td class="paiement">' . $service ['paye'] . '</td>';
		$type_service_string = NULL;
		foreach ($this->list_types_services as $type_service){
			if($type_service['id_type_service'] == $service['id_type_service']){
				$type_service_string = $type_service['libelle_type_service'];
			}
		}
		echo '<td>' . $type_service_string. '</td>';
		// get the poste name
		echo '
		<td>
		<span class="tip" >
		<a  title="Edit" class="edit" href="';
		echo $this->url ( array ('id' => $service ['id_service'] ), 'servicemodify' );
		echo '">
		<img src="images/icon/icon_edit.png" >
		</a>
		</span>
		<span class="tip" >
		<a id="' . $i . '" class="Delete"  name="Band ring" title="Delete">
		<img src="images/icon/icon_delete.png">
		</a>
		</span>
		</td>
		</tr>';
		$i ++;
}
echo '</tbody>
</table>
</div>
</form>
</div>
</div><!--tab1-->

</div>
</div><!-- End UITab -->
<!-- clear fix -->
<div class="clear"></div>
';
?>