<form action="#">
	<div class="section alphaonly">
		<label>Client<small>Text custom</small></label>
		<div>
			<input name="text[]" type="text" class="medium" maxlength="20"
				value="khalifa  rmili" readonly="readonly">
		</div>
	</div>

	<div class="section alphaonly">
		<label>Description<small>Text custom</small></label>
		<div>
			<textarea name="description" readonly="readonly">Ceci est une description d'un rpojet</textarea>
		</div>
	</div>

	<div class="section">
		<label>Prix </label>
		<div>
			<input type="text" id="sCur" value="10" readonly="readonly" />
		</div>
	</div>
	<div class="section alphaonly">
		<label>Date debut<small>La date de debut du service</small></label>
		<div>
			<input name="d_d" type="text" class="medium" value="12/05/2012"
				readonly="readonly">
		</div>
	</div>

	<div class="section alphaonly">
		<label>Date fin<small>La date fin du service</small></label>
		<div>
			<input name="d_f" type="text" class="medium" value="12/06/2012"
				DISABLED>
		</div>
	</div>
	<div class="section alphaonly">
		<label>Date d'Activation<small>La date d'activation du service</small></label>
		<div>
			<input name="d_d" type="text" class="medium" value="12/05/2012"
				readonly="readonly">
		</div>
	</div>
	<div class="section alphaonly">
		<label>Date de Desactivation<small>La date prevu pour la desactivation du service</small></label>
		<div>
			<input name="d_f" type="text" class="medium" value="12/06/2012"
				DISABLED>
		</div>
	</div>
	<div class="section">
		<label>Status<small>Veuillez definir un status initial pour ce projet</small></label>
		<div>
			<input type="checkbox" id="preOrder" name="preOrder" class="preOrder"
				value="1" /> <span class="f_help"></span>
		</div>
	</div>


</form>
