
<script type="text/javascript"
	src="<?php echo $this->baseUrl('js/occupation.js');?>"></script>


<form id="validation" class="f_o_add">
	<div class="section textonly">
		<label> Nom <small></small></label>
		<div>
			<input id="f_required" name="nom_occup" type="text"
				class="validate[required] medium">
		</div>
	</div>
	<div class="section last">
		<div>
			<a class="button green morph add_occup">Ajouter</a> 
		</div>
	</div>
	
</form>