<!DOCTYPE html>
<html>

<!-- Mirrored from zicedemo.com/ by HTTrack Website Copier/3.x [XR&CO'2010], Sun, 08 Apr 2012 15:13:56 GMT -->
<head>
        <meta charset="utf-8" />
		<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;" />
<title>TYNEXADMIN</title>
        <!--[if lt IE 9]>
          <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
<link href="<?php echo $this->baseUrl('css/zice.style.css');?>" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->baseUrl('css/icon.css');?>" rel="stylesheet" type="text/css" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('components/tipsy/tipsy.css');?>" media="all"/>
<style type="text/css">
html {
	background-image: none;
}
#versionBar {
	background-color:#212121;
	position:fixed;
	width:100%;
	height:35px;
	bottom:0;
	left:0;
	text-align:center;
	line-height:35px;
	z-index:11;
}
.copyright{
	text-align:center; font-size:10px; color:#CCC;
}
.copyright a{
	color:#A31F1A; text-decoration:none
}    
</style>
</head>
<body >
         
<div id="alertMessage" class="error"></div>
<div id="successLogin"></div>
<div class="text_success"><img src="images/loadder/loader_green.gif"  alt="ziceAdmin" /><span>Veuillez Patienter</span></div>

<div id="login" >
  <div class="inner">
  <div class="logo" ><img src="<?php echo $this->baseUrl('images/logo/logo_login.png');?>" alt="ziceAdmin" /></div>
  <div class="formLogin">
   <form name="formLogin"  id="formLogin" action="/authentication/login" method="POST">

          <div class="tip">
				<input name="username" type="text"  id="username_id"  title="Utilisateur"   />
          </div>
          <div class="tip">
				<input name="password" type="password" id="password"   title="Mot de passe"  />
          </div>

          <div class="loginButton">
           <div style="float:left; padding:3px 0; margin-right:-12px;">
              <div> 
           			<?php echo $this->message;?>
              </div>
			  
            </div>
			<div style="float:right; padding:3px 0; margin-right:-12px;">
              <div> 
                <ul class="uibutton-group">
                   <li><a class="button green morph connexion">Se connecter</a></li>
				  
               </ul>
              </div>
			  
            </div>
			<div class="clear"></div>
		  </div>

    </form>
  </div>
</div>
  <div class="clear"></div>
  <div class="shadow"></div>
</div>

<!--Login div-->
<div class="clear"></div>
<div id="versionBar" >
  <div class="copyright" ><span class="tip"></span> </div>
  <!-- // copyright-->
</div>
<!-- Link JScript-->
<script type="text/javascript" src="<?php echo $this->baseUrl('js/jquery.min.js');?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('components/effect/jquery-jrumble.js');?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('components/ui/jquery.ui.min.js');?>"></script>     
<script type="text/javascript" src="<?php echo $this->baseUrl('components/tipsy/jquery.tipsy.js');?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('components/checkboxes/iphone.check.js');?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/login.js');?>"></script>
<script type="text/javascript" >
$(document).ready(function(){
	$('.connexion').click(function() {
		  $('#formLogin').submit();
		});
	
});

</script>
</body>

<!-- Mirrored from zicedemo.com/ by HTTrack Website Copier/3.x [XR&CO'2010], Sun, 08 Apr 2012 15:14:28 GMT -->
</html>
