<!DOCTYPE html>
<html>

<!-- Mirrored from zicedemo.com/404.html by HTTrack Website Copier/3.x [XR&CO'2010], Sun, 08 Apr 2012 14:51:42 GMT -->
<head>
<meta charset="utf-8" />
<title>TynexMedia&trade; admin version 1.0 online</title>
<title>TYNEXADMIN version 1.0 online</title>
<link href="<?php echo $this->baseUrl('css/zice.style.css');?>"
	rel="stylesheet" type="text/css" />
<link rel="stylesheet" type="text/css"
	href="<?php echo $this->baseUrl('components/tipsy/tipsy.css');?>"
	media="all" />
<script type="text/javascript"
	src="<?php echo $this->baseUrl('js/jquery.min.js');?>"></script>
<script type="text/javascript"
	src="<?php echo $this->baseUrl('js/jquery.cycle.all.js');?>"></script>
<script type="text/javascript"
	src="<?php echo $this->baseUrl('components/tipsy/jquery.tipsy.js');?>"></script>
<script type="text/javascript"
	src="<?php echo $this->baseUrl('components/effect/jquery-jrumble.js');?>"></script>
<script type="text/javascript">
          jQuery(function($){
			 $('#tv-wrap').jrumble({ x: 4,y: 0,rotation: 0 });	
			$('#tv-wrap').trigger('startRumble');		  
              $('.slides').addClass('active').cycle({
                  fx:     'none',
                  speed:   1,
                  timeout: 70
              }).cycle("resume");	
          });
</script>
<style type="text/css">
html {
	background-image: none;
}

#versionBar {
	background-color: #212121;
	position: fixed;
	width: 100%;
	height: 35px;
	bottom: 0;
	left: 0;
	text-align: center;
	line-height: 35px;
}

.copyright {
	text-align: center;
	font-size: 10px;
	color: #CCC;
}

.copyright a {
	color: #A31F1A;
	text-decoration: none
}
</style>
</head>
<body class="error">
	<div class="errorpage">
		<div id="tv-wrap">
			<img src="<?php echo $this->baseUrl('images/tv.png');?>" width="300"
				height="273" id="tv" />
			<div class="slideshow-block">
				<a href="dashboard.html" class="link"></a>
				<ul class="slides">
					<li><img
						src="<?php echo $this->baseUrl('images/pageserror/1.jpg');?>" /></li>
					<li><img
						src="<?php echo $this->baseUrl('images/pageserror/2.jpg');?>" /></li>
					<li><img
						src="<?php echo $this->baseUrl('images/pageserror/3.jpg');?>" /></li>
					<li><img
						src="<?php echo $this->baseUrl('images/pageserror/4.jpg');?>" /></li>
					<li><img
						src="<?php echo $this->baseUrl('images/pageserror/5.jpg');?>" /></li>
					<li><img
						src="<?php echo $this->baseUrl('images/pageserror/6.jpg');?>" /></li>
					<li><img
						src="<?php echo $this->baseUrl('images/pageserror/7.jpg');?>" /></li>
					<li><img
						src="<?php echo $this->baseUrl('images/pageserror/8.jpg');?>" /></li>
					<li><img
						src="<?php echo $this->baseUrl('images/pageserror/9.jpg');?>" /></li>
					<li><img
						src="<?php echo $this->baseUrl('images/pageserror/10.jpg');?>" /></li>
					<li><img
						src="<?php echo $this->baseUrl('images/pageserror/11.jpg');?>" /></li>
					<li><img
						src="<?php echo $this->baseUrl('images/pageserror/12.jpg');?>" /></li>
				</ul>
			</div>
		</div>
		<div id="text">
			 
			<?php echo $this->layout()->content; ?>
			
			

		</div>

		<center>

			<a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index' ),'default',true);?>">Retour à l'accueil</a>

			

		</center>

	</div>
	<div class="clear"></div>
	<div id="versionBar">
		
		
	</div>
	<script type="text/javascript">
var text = document.getElementById('text'),
	body = document.body,
	steps = 7;
function threedee (e) {
	var x = Math.round(steps / (window.innerWidth / 2) * (window.innerWidth / 2 - e.clientX)),
		y = Math.round(steps / (window.innerHeight / 2) * (window.innerHeight / 2 - e.clientY)),
		shadow = '',
		color = 190,
		radius = 3,
		i;	
	for (i=0; i<steps; i++) {
		tx = Math.round(x / steps * i);
		ty = Math.round(y / steps * i);
		if (tx || ty) {
			color -= 3 * i;
			shadow += tx + 'px ' + ty + 'px 0 rgb(' + color + ', ' + color + ', ' + color + '), ';
		}
	}
	shadow += x + 'px ' + y + 'px 1px rgba(0,0,0,.2), ' + x*2 + 'px ' + y*2 + 'px 6px rgba(0,0,0,.3)';	
	text.style.textShadow = shadow;
	text.style.webkitTransform = 'translateZ(0) rotateX(' + y*1.5 + 'deg) rotateY(' + -x*1.5 + 'deg)';
	text.style.MozTransform = 'translateZ(0) rotateX(' + y*1.5 + 'deg) rotateY(' + -x*1.5 + 'deg)';
}
document.addEventListener('mousemove', threedee, false);
</script>
</body>

<!-- Mirrored from zicedemo.com/404.html by HTTrack Website Copier/3.x [XR&CO'2010], Sun, 08 Apr 2012 14:52:09 GMT -->
</html>
